### ISSUE TITLE
Project: Symfony Bundle

### ISSUE THREAD

**Issue by scrummer** [LabyMod/discord-webhook#11]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

## Description
Create a symfony bundle with or within this library.
Goals are:
* Configure channels in yaml directly
* Resolve the webhook from DI
* Make endpoint configuration simpler

## Todo
- [ ] Evaluation: Within this library or as separate bundle?
- [ ] Basic symfony Bundle structure
- [ ] Configuration boilerplate according to: https://symfony.com/doc/current/components/config/definition.html#adding-node-definitions-to-the-tree
  - [ ] client configurations (maybe with bot name and avatar?)
  - [ ] url configurations
  - [ ] Support for different clients, similar to: https://symfony.com/doc/current/http_client.html#scoping-client
- [ ] Define webhook class as service

**Comment by scrummer** [comment]
See https://github.com/LabyMod/discord-webhook-bundle
